<%@ taglib uri="/tags" prefix="pi" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" >
<head>
	<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
	<title>Implicit Association Test</title>
	<script type="text/javascript">
		function hlght() { if (document.getElementById) document.getElementById('gttt').style.backgroundColor = "#ffffff" ; }
		function llght() { if (document.getElementById) document.getElementById('gttt').style.backgroundColor = "#c2d2dd" ; }
	</script>
	<link rel="stylesheet" href="/implicit/demo/demo.css" type="text/css" />
	<script language="javascript" type="text/javascript" src="/implicit/common/en-us/js/task.js"></script>
	<script language="javascript" type="text/javascript" src="/implicit/common/en-us/js/closeWindow.js"></script>
	<style type="text/css">
		.hi { background-color: #eaf1dc; }
	</style>
</head>
<body>
<table width="100%" cellpadding="0" cellspacing="0" border="0">
<tr><td align="center">
<table width="664" border="0" cellpadding="0" cellspacing="0" id="header">
<tr class="dblu">
	<td align="left"><a href="/implicit"><img src="/implicit/demo/images/demhead.gif" width="467" height="49" alt="Implicit Association Test" /></a></td>
	<td align="center"><div id="gttt"><a href="/implicit/demo/featuredtask.html" onmouseover="hlght()" onmouseout="llght()">Featured<br />Task</a></div></td>
</tr>
</table>

<table width="664" border="0" cellpadding="0" cellspacing="0" id="menu">
				<tr class="lblu" align="center">
				<td><a class="menlnk" href="/implicit/research/">Try a Study</a></td>
				<td><a class="menlnk" href="/implicit/demo/takeatest.html">Take a Demo Test</a></td>
				<td><a class="menlnk" href="/implicit/demo/background/index.jsp">Background</a></td>
				<td><a class="menlnk" href="/implicit/demo/support/index.jsp">Tech Support</a></td>
				<td><a class="menlnk" href="/implicit/demo/background/thescientists.html">The Scientists</a></td>
				<td><a class="menlnk" href="http://www.projectimplicit.net/">Project Implicit</a></td>
</tr>
</table>

<br />

<table class="core" width="600" cellpadding="10" cellspacing="0" border="0">
<tr>
	<td align="left"><p align="center" class="text"><strong>You have completed the Gender - Science IAT.</strong></p>

<div align="center" class="text"><strong>Your Result</strong></div>
<div class="hi"><h2><pi:print result="feedback">$result</pi:print></h2></div>

	<p class="text">Thank you for your participation. Just below is a breakdown of the scores generated by others. Most respondents find it 
	easier to associate <em>Male</em> with <em>Science</em> and <em>Female</em> with <em>Liberal Arts</em> compared to the reverse.</p>
	<table width="160" border="0" cellpadding="0" cellspacing="1" align="right">
<tr>
<td>
<table width="100%" border="0" cellpadding="2" cellspacing="1">
<tr>
<td><a href="JavaScript:void window.open('/implicit/demo/background/gensciinfo.html', 'GenSciInfo', 'SCROLLBARS=YES,RESIZABLE=YES,WIDTH=500,HEIGHT=650');"><img src="/implicit/demo/images/genscibreakdown.gif" alt="gensci score distribution" /></a></td>
</tr>
</table>
</td>
</tr>
</table>
	<p class="text">Many of the questions 
	that you answered on the previous page have been addressed in research over the last 10 years. For example, the order that you performed the response 
	pairing is influential, but procedural corrections largely eliminate that influence (see <a href="/implicit/demo/background/faqs.html#faq1">FAQ #1</a>). 
	Each visitor to the site completes the task in a randomized order. If you would like to learn more about the IAT, please visit the <a href="/implicit/demo/background/">FAQs and background information</a> 
	section.</p>
	<p class="text">You are welcome to try <a href="/implicit/demo/selectatest.jsp">additional demonstration tasks</a>, 
	and we encourage you to register (easy) for the <a href="/implicit/research/">research site</a> where you will gain access to 
	studies about more than 100 topics about social groups, personality, pop culture, and more.</p></td>
</tr>
	<tr>
		<td align="center"><p class="text"><a href="/implicit/demo/background/faqs.html">FAQs</a> || <a href="/implicit/research/">Research site</a> || <a href="/implicit/demo/">Demo site</a> || <a href="/implicit/">Project Implicit Home</a></p></td>
	</tr>
</table>

<table width="600" cellpadding="10" cellspacing="0" border="0">
<tr><td align="center"><p class="smltext"><a href="/implicit/demo/copyright.html">Copyright &copy; IAT Corp.</a></p></td>
</tr></table></td>
</tr>
</table>
</body>
</html>